// This file is auto-generated by @hey-api/openapi-ts

export const AssetResponseSchema = {
    properties: {
        asset_id: {
            type: 'string',
            format: 'uuid',
            title: 'Asset Id',
            description: 'Unique asset identifier'
        },
        file_name: {
            type: 'string',
            title: 'File Name',
            description: 'Original filename (sanitized)'
        },
        file_size_bytes: {
            type: 'integer',
            title: 'File Size Bytes',
            description: 'File size in bytes'
        },
        mime_type: {
            type: 'string',
            title: 'Mime Type',
            description: 'MIME type of the file'
        },
        checksum: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Checksum',
            description: 'MD5 checksum for integrity verification'
        },
        object_key: {
            type: 'string',
            title: 'Object Key',
            description: 'MinIO object key (storage path)'
        },
        bucket: {
            type: 'string',
            title: 'Bucket',
            description: 'MinIO bucket name'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id',
            description: 'Owner user ID'
        },
        tenant_id: {
            type: 'string',
            format: 'uuid',
            title: 'Tenant Id',
            description: 'Tenant ID'
        },
        is_deleted: {
            type: 'boolean',
            title: 'Is Deleted',
            description: 'Soft delete flag'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At',
            description: 'Upload timestamp'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At',
            description: 'Last update timestamp'
        }
    },
    type: 'object',
    required: ['asset_id', 'file_name', 'file_size_bytes', 'mime_type', 'checksum', 'object_key', 'bucket', 'user_id', 'tenant_id', 'is_deleted', 'created_at', 'updated_at'],
    title: 'AssetResponse',
    description: `Response schema for asset operations (AC: #6).

Returned on successful upload with 201 Created.`,
    example: {
        asset_id: '550e8400-e29b-41d4-a716-446655440000',
        bucket: 'assets',
        checksum: 'd41d8cd98f00b204e9800998ecf8427e',
        created_at: '2025-12-17T10:30:00Z',
        file_name: 'textbook.pdf',
        file_size_bytes: 15728640,
        is_deleted: false,
        mime_type: 'application/pdf',
        object_key: 'publisher/tenant-123/asset-456/textbook.pdf',
        tenant_id: '770e8400-e29b-41d4-a716-446655440002',
        updated_at: '2025-12-17T10:30:00Z',
        user_id: '660e8400-e29b-41d4-a716-446655440001'
    }
} as const;

export const BatchDownloadRequestSchema = {
    properties: {
        asset_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            maxItems: 100,
            minItems: 1,
            title: 'Asset Ids',
            description: 'List of asset IDs to include in batch download (1-100 assets)',
            examples: [['550e8400-e29b-41d4-a716-446655440001', '550e8400-e29b-41d4-a716-446655440002']]
        }
    },
    type: 'object',
    required: ['asset_ids'],
    title: 'BatchDownloadRequest',
    description: `Request schema for batch download endpoint (AC: #1, #11, #12).

Validates:
- Non-empty asset list (min 1)
- Maximum 100 assets per request
- No duplicate asset IDs

References:
    - Task 2.2: Request schema with validation
    - AC: #11 (empty list), #12 (too many assets)`,
    example: {
        asset_ids: ['550e8400-e29b-41d4-a716-446655440001', '550e8400-e29b-41d4-a716-446655440002', '550e8400-e29b-41d4-a716-446655440003']
    }
} as const;

export const BatchDownloadResponseSchema = {
    properties: {
        download_url: {
            type: 'string',
            title: 'Download Url',
            description: 'Presigned URL to download the generated ZIP file'
        },
        expires_at: {
            type: 'string',
            format: 'date-time',
            title: 'Expires At',
            description: 'URL and ZIP file expiration time (1 hour from creation)'
        },
        file_name: {
            type: 'string',
            title: 'File Name',
            description: 'Generated ZIP file name'
        },
        file_count: {
            type: 'integer',
            minimum: 1,
            title: 'File Count',
            description: 'Number of files included in the ZIP'
        },
        total_size_bytes: {
            type: 'integer',
            minimum: 0,
            title: 'Total Size Bytes',
            description: 'Total size of all files before compression'
        },
        compressed_size_bytes: {
            type: 'integer',
            minimum: 0,
            title: 'Compressed Size Bytes',
            description: 'Size of the ZIP file'
        }
    },
    type: 'object',
    required: ['download_url', 'expires_at', 'file_name', 'file_count', 'total_size_bytes', 'compressed_size_bytes'],
    title: 'BatchDownloadResponse',
    description: `Response schema for batch download endpoint (AC: #4).

Contains:
- Presigned download URL for the generated ZIP
- Expiration time (1 hour, AC: #5, #8)
- File metadata (count, sizes)

References:
    - Task 2.3: Response schema
    - AC: #4 (download URL), #5 (expiry)`,
    example: {
        compressed_size_bytes: 41943040,
        download_url: 'https://minio.example.com/assets/temp/batch-downloads/batch-download-20251217-100000-abc123.zip?...',
        expires_at: '2025-12-17T12:00:00Z',
        file_count: 3,
        file_name: 'batch-download-20251217-100000-abc123.zip',
        total_size_bytes: 52428800
    }
} as const;

export const Body_assets_upload_fileSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File',
            description: 'File to upload'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_assets-upload_file'
} as const;

export const Body_auth_loginSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_auth-login'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const DownloadResponseSchema = {
    properties: {
        download_url: {
            type: 'string',
            title: 'Download Url',
            description: 'Presigned URL for direct MinIO download (1-hour TTL)',
            example: 'https://minio.example.com/assets/...?X-Amz-Signature=...'
        },
        expires_at: {
            type: 'string',
            format: 'date-time',
            title: 'Expires At',
            description: 'URL expiration time in ISO-8601 format',
            example: '2025-12-17T12:00:00Z'
        },
        file_name: {
            type: 'string',
            title: 'File Name',
            description: 'Original file name',
            example: 'document.pdf'
        },
        file_size: {
            type: 'integer',
            title: 'File Size',
            description: 'File size in bytes',
            example: 1234567
        },
        mime_type: {
            type: 'string',
            title: 'Mime Type',
            description: 'MIME type of the file',
            example: 'application/pdf'
        }
    },
    type: 'object',
    required: ['download_url', 'expires_at', 'file_name', 'file_size', 'mime_type'],
    title: 'DownloadResponse',
    description: `Response schema for asset download endpoint.

Returns presigned download URL with complete file metadata.

References:
- AC: #3 (enhanced download response)
- Task 2.2 (schema fields)`,
    example: {
        download_url: 'https://minio.example.com/assets/uuid/file.pdf?X-Amz-Algorithm=...',
        expires_at: '2025-12-17T12:00:00Z',
        file_name: 'document.pdf',
        file_size: 1234567,
        mime_type: 'application/pdf'
    }
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HealthCheckResponseSchema = {
    properties: {
        status: {
            type: 'string',
            enum: ['healthy', 'unhealthy'],
            title: 'Status'
        },
        database: {
            type: 'string',
            enum: ['ok', 'error'],
            title: 'Database'
        },
        minio: {
            type: 'string',
            enum: ['ok', 'error'],
            title: 'Minio'
        },
        timestamp: {
            type: 'string',
            format: 'date-time',
            title: 'Timestamp'
        }
    },
    type: 'object',
    required: ['status', 'database', 'minio', 'timestamp'],
    title: 'HealthCheckResponse',
    description: 'Health check response schema.'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate',
    description: 'Properties to receive on item creation.'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic',
    description: 'Properties to return via API.'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate',
    description: 'Properties to receive on item update.'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic',
    description: 'Paginated list of items.'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message',
    description: 'Generic message response.'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword',
    description: 'Properties for password reset.'
} as const;

export const PreviewResponseSchema = {
    properties: {
        preview_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Preview Url',
            description: 'Presigned URL for preview (null for unsupported types)',
            examples: ['https://minio.example.com/assets/photo.jpg?signature=abc123']
        },
        preview_type: {
            '$ref': '#/components/schemas/PreviewType',
            description: 'Type of preview: image, video, audio, pdf, document, unsupported',
            examples: ['image']
        },
        expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expires At',
            description: 'URL expiration time (ISO-8601, null for unsupported types)',
            examples: ['2025-12-18T12:00:00Z']
        },
        mime_type: {
            type: 'string',
            title: 'Mime Type',
            description: 'Original MIME type of the asset',
            examples: ['image/jpeg']
        },
        file_name: {
            type: 'string',
            title: 'File Name',
            description: 'Original file name',
            examples: ['photo.jpg']
        },
        file_size: {
            type: 'integer',
            minimum: 0,
            title: 'File Size',
            description: 'File size in bytes',
            examples: [1234567]
        },
        supports_inline: {
            type: 'boolean',
            title: 'Supports Inline',
            description: 'Whether the asset can be previewed inline in browser',
            examples: [true]
        }
    },
    type: 'object',
    required: ['preview_type', 'mime_type', 'file_name', 'file_size', 'supports_inline'],
    title: 'PreviewResponse',
    description: `Response schema for asset preview endpoint (AC: #1, #8, #9).

Returns a presigned URL appropriate for inline preview based on asset type.
For unsupported types, returns null URL with file metadata only.

Attributes:
    preview_url: Presigned URL for preview (null for unsupported types)
    preview_type: Type of preview (image, video, audio, pdf, document, unsupported)
    expires_at: URL expiration timestamp (null for unsupported types)
    mime_type: Original MIME type of the asset
    file_name: Original file name
    file_size: File size in bytes
    supports_inline: Whether the asset can be previewed inline in browser`,
    examples: [
        {
            expires_at: '2025-12-18T12:00:00Z',
            file_name: 'photo.jpg',
            file_size: 1234567,
            mime_type: 'image/jpeg',
            preview_type: 'image',
            preview_url: 'https://minio.example.com/assets/photo.jpg?signature=abc123',
            supports_inline: true
        },
        {
            file_name: 'archive.zip',
            file_size: 9876543,
            mime_type: 'application/zip',
            preview_type: 'unsupported',
            supports_inline: false
        }
    ]
} as const;

export const PreviewTypeSchema = {
    type: 'string',
    enum: ['image', 'video', 'audio', 'pdf', 'document', 'unsupported'],
    title: 'PreviewType',
    description: `Types of asset previews supported.

Determines how the frontend should render the preview:
- image: Display in <img> tag
- video: Display in <video> tag with controls
- audio: Display in <audio> tag with controls
- pdf: Display in <iframe> or PDF.js viewer
- document: Display in code/text viewer
- unsupported: No inline preview, download only`
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const RefreshTokenRequestSchema = {
    properties: {
        refresh_token: {
            type: 'string',
            title: 'Refresh Token'
        }
    },
    type: 'object',
    required: ['refresh_token'],
    title: 'RefreshTokenRequest',
    description: 'Request body for token refresh endpoint (AC: #7).'
} as const;

export const SignedURLResponseSchema = {
    properties: {
        url: {
            type: 'string',
            title: 'Url',
            description: 'Presigned URL for direct MinIO access'
        },
        expires_at: {
            type: 'string',
            format: 'date-time',
            title: 'Expires At',
            description: 'URL expiration time (ISO-8601)'
        },
        type: {
            type: 'string',
            enum: ['download', 'upload', 'stream'],
            title: 'Type',
            description: 'Type of signed URL operation'
        }
    },
    type: 'object',
    required: ['url', 'expires_at', 'type'],
    title: 'SignedURLResponse',
    description: `Response schema for signed URL generation (AC: #9).

Returned when a presigned URL is successfully generated.`,
    example: {
        expires_at: '2025-12-17T12:00:00Z',
        type: 'download',
        url: 'http://minio:9000/assets/publisher/tenant-id/asset-id/file.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=...'
    }
} as const;

export const StreamingURLResponseSchema = {
    properties: {
        stream_url: {
            type: 'string',
            title: 'Stream Url',
            description: 'Presigned URL for MinIO streaming (supports HTTP Range requests)'
        },
        expires_at: {
            type: 'string',
            format: 'date-time',
            title: 'Expires At',
            description: 'URL expiration time (ISO-8601)'
        },
        mime_type: {
            type: 'string',
            title: 'Mime Type',
            description: 'Content MIME type (video/* or audio/*)'
        },
        file_size: {
            type: 'integer',
            title: 'File Size',
            description: 'Total file size in bytes'
        },
        file_name: {
            type: 'string',
            title: 'File Name',
            description: 'Original file name'
        },
        duration_seconds: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration Seconds',
            description: 'Media duration in seconds (if available in metadata)'
        }
    },
    type: 'object',
    required: ['stream_url', 'expires_at', 'mime_type', 'file_size', 'file_name'],
    title: 'StreamingURLResponse',
    description: `Response schema for streaming endpoint.

Returns presigned URL for video/audio streaming with HTTP Range support.
URL is valid for 1 hour (PRESIGNED_URL_STREAM_EXPIRES_SECONDS).

References:
- Task 2: Streaming response schema
- AC: #2, #6 (stream URL with expiration and metadata)`,
    example: {
        duration_seconds: 3600,
        expires_at: '2025-12-18T12:00:00Z',
        file_name: 'lesson-01.mp4',
        file_size: 52428800,
        mime_type: 'video/mp4',
        stream_url: 'https://minio.example.com/assets/lesson-01.mp4?X-Amz-Algorithm=...'
    }
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token',
    description: 'JSON payload containing access token (legacy, for backward compatibility).'
} as const;

export const TokenResponseSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        refresh_token: {
            type: 'string',
            title: 'Refresh Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        },
        expires_in: {
            type: 'integer',
            title: 'Expires In'
        }
    },
    type: 'object',
    required: ['access_token', 'refresh_token', 'expires_in'],
    title: 'TokenResponse',
    description: 'Full token response with access and refresh tokens (AC: #1, #7).'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword',
    description: 'Properties for password update.'
} as const;

export const UploadURLRequestSchema = {
    properties: {
        file_name: {
            type: 'string',
            maxLength: 255,
            title: 'File Name',
            description: 'Name of the file to upload'
        },
        mime_type: {
            type: 'string',
            maxLength: 127,
            title: 'Mime Type',
            description: 'MIME type of the file'
        },
        file_size: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'File Size',
            description: 'Size of the file in bytes'
        }
    },
    type: 'object',
    required: ['file_name', 'mime_type', 'file_size'],
    title: 'UploadURLRequest',
    description: `Request schema for presigned upload URL generation.

Validates file_name and mime_type before generating upload URL.`,
    example: {
        file_name: 'textbook.pdf',
        file_size: 15728640,
        mime_type: 'application/pdf'
    }
} as const;

export const UploadURLResponseSchema = {
    properties: {
        url: {
            type: 'string',
            title: 'Url',
            description: 'Presigned URL for direct MinIO upload'
        },
        expires_at: {
            type: 'string',
            format: 'date-time',
            title: 'Expires At',
            description: 'URL expiration time (ISO-8601)'
        },
        type: {
            type: 'string',
            const: 'upload',
            title: 'Type',
            description: 'URL type',
            default: 'upload'
        },
        asset_id: {
            type: 'string',
            format: 'uuid',
            title: 'Asset Id',
            description: 'Pre-generated asset ID for the upload'
        },
        object_key: {
            type: 'string',
            title: 'Object Key',
            description: 'MinIO object key where file will be stored'
        }
    },
    type: 'object',
    required: ['url', 'expires_at', 'asset_id', 'object_key'],
    title: 'UploadURLResponse',
    description: `Response schema for presigned upload URL generation.

Includes the upload URL, expiration, and the asset_id for the new asset.`,
    example: {
        asset_id: '550e8400-e29b-41d4-a716-446655440000',
        expires_at: '2025-12-17T10:15:00Z',
        object_key: 'publisher/tenant-id/asset-id/file.pdf',
        type: 'upload',
        url: 'http://minio:9000/assets/publisher/tenant-id/asset-id/file.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=...'
    }
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'student'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        tenant_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tenant Id'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate',
    description: 'Properties to receive via API on user creation.'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'student'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        tenant_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tenant Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['email', 'id', 'tenant_id', 'created_at', 'updated_at'],
    title: 'UserPublic',
    description: 'Properties to return via API.'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister',
    description: 'Properties for user self-registration.'
} as const;

export const UserRoleSchema = {
    type: 'string',
    enum: ['admin', 'supervisor', 'publisher', 'school', 'teacher', 'student'],
    title: 'UserRole',
    description: 'User roles for role-based access control (RBAC).'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/UserRole'
                },
                {
                    type: 'null'
                }
            ]
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        tenant_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tenant Id'
        }
    },
    type: 'object',
    title: 'UserUpdate',
    description: 'Properties to receive via API on user update, all optional.'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe',
    description: 'Properties for user to update their own profile.'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic',
    description: 'Paginated list of users.'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;