// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { AssetsUploadFileData, AssetsUploadFileResponse, AuthLoginData, AuthLoginResponse, AuthRefreshTokenData, AuthRefreshTokenResponse, BatchDownloadBatchDownloadAssetsData, BatchDownloadBatchDownloadAssetsResponse, DownloadDownloadAssetData, DownloadDownloadAssetResponse, HealthHealthCheckResponse, ItemsReadItemsData, ItemsReadItemsResponse, ItemsCreateItemData, ItemsCreateItemResponse, ItemsReadItemData, ItemsReadItemResponse, ItemsUpdateItemData, ItemsUpdateItemResponse, ItemsDeleteItemData, ItemsDeleteItemResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PreviewPreviewAssetData, PreviewPreviewAssetResponse, PrivateCreateUserData, PrivateCreateUserResponse, SignedUrlsGetDownloadUrlData, SignedUrlsGetDownloadUrlResponse, SignedUrlsGetStreamUrlData, SignedUrlsGetStreamUrlResponse, SignedUrlsGetUploadUrlData, SignedUrlsGetUploadUrlResponse, StreamingStreamAssetData, StreamingStreamAssetResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class AssetsService {
    /**
     * Upload a single file
     * Upload a single file to user's storage area.
     *
     * **Validation:**
     * - MIME type must be in allowed whitelist (AC: #2)
     * - File size must not exceed type-specific limits (AC: #1)
     * - Videos: 10GB max
     * - Images: 500MB max
     * - Other: 5GB max
     *
     * **Process:**
     * 1. Validates file type and size
     * 2. Uploads to MinIO with streaming (no full memory buffering)
     * 3. Calculates MD5 checksum during upload
     * 4. Creates asset metadata in PostgreSQL
     * 5. Creates audit log entry
     *
     * **Returns:**
     * - 201 Created with asset metadata on success
     * - 400 Bad Request with INVALID_FILE_TYPE if MIME type not allowed
     * - 400 Bad Request with FILE_TOO_LARGE if size exceeds limit
     * - 401 Unauthorized if not authenticated
     * - 429 Too Many Requests if rate limit exceeded
     * @param data The data for the request.
     * @param data.formData
     * @returns AssetResponse File uploaded successfully
     * @throws ApiError
     */
    public static uploadFile(data: AssetsUploadFileData): CancelablePromise<AssetsUploadFileResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/assets/upload',
            formData: data.formData,
            mediaType: 'multipart/form-data',
            errors: {
                400: 'Validation error (invalid type or size)',
                401: 'Not authenticated',
                422: 'Validation Error',
                429: 'Rate limit exceeded'
            }
        });
    }
}

export class AuthService {
    /**
     * Login
     * OAuth2 compatible login endpoint.
     *
     * Accepts email/password and returns access + refresh tokens.
     *
     * **Rate Limited:** Configurable via RATE_LIMIT_LOGIN (default: 5/minute per IP)
     *
     * - **username**: User's email address
     * - **password**: User's password
     *
     * Returns:
     * TokenResponse with access_token, refresh_token, token_type, expires_in
     *
     * Raises:
     * - 401: Invalid credentials or inactive account
     * - 429: Too many requests (rate limit exceeded)
     * @param data The data for the request.
     * @param data.formData
     * @returns TokenResponse Successful Response
     * @throws ApiError
     */
    public static login(data: AuthLoginData): CancelablePromise<AuthLoginResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/auth/login',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Refresh Token
     * Refresh access token using refresh token.
     *
     * Implements token rotation - new refresh token is issued with each refresh (AC: #7).
     *
     * - **refresh_token**: Valid refresh token from previous login
     *
     * Returns:
     * TokenResponse with new access_token and refresh_token
     *
     * Raises:
     * - 401: Invalid or expired refresh token
     * @param data The data for the request.
     * @param data.requestBody
     * @returns TokenResponse Successful Response
     * @throws ApiError
     */
    public static refreshToken(data: AuthRefreshTokenData): CancelablePromise<AuthRefreshTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/auth/refresh',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class BatchDownloadService {
    /**
     * Download multiple assets as ZIP
     * Download multiple assets as a single ZIP file.
     *
     * **Process:**
     * 1. Validates user has permission for all requested assets (AC: #1)
     * 2. Generates a ZIP file containing all assets (AC: #2)
     * 3. Uses streaming to avoid memory buffering (AC: #3)
     * 4. Uploads ZIP to temporary storage with 1-hour expiry (AC: #5, #8)
     * 5. Returns presigned download URL (AC: #4, #7)
     * 6. Creates audit log entry (AC: #6)
     *
     * **Request Validation:**
     * - Minimum 1 asset required (AC: #11)
     * - Maximum 100 assets per request (AC: #12)
     * - No duplicate asset IDs allowed
     * - All assets must exist (AC: #10)
     * - User must have permission for all assets (AC: #9)
     *
     * **ZIP File Details:**
     * - Files retain original names
     * - ZIP uses DEFLATE compression
     * - Stored at: `temp/batch-downloads/{timestamp}-{uuid}.zip`
     * - Automatically deleted after 1 hour
     *
     * **Permissions:**
     * - Owner can download their own assets
     * - Admin and Supervisor can download any assets
     *
     * **Error Codes:**
     * - 400 BAD_REQUEST: Empty list or >100 assets (AC: #11, #12)
     * - 403 PERMISSION_DENIED: Lacks permission for one or more assets (AC: #9)
     * - 404 ASSET_NOT_FOUND: One or more assets don't exist (AC: #10)
     * - 429 TOO_MANY_REQUESTS: Rate limit exceeded
     *
     * **Example Request:**
     * ```json
     * {
     * "asset_ids": [
     * "550e8400-e29b-41d4-a716-446655440001",
     * "550e8400-e29b-41d4-a716-446655440002",
     * "550e8400-e29b-41d4-a716-446655440003"
     * ]
     * }
     * ```
     *
     * **Example Response:**
     * ```json
     * {
     * "download_url": "https://minio.example.com/assets/temp/batch-downloads/...",
     * "expires_at": "2025-12-18T12:00:00Z",
     * "file_name": "batch-download-20251218-100000-abc123.zip",
     * "file_count": 3,
     * "total_size_bytes": 10485760,
     * "compressed_size_bytes": 8388608
     * }
     * ```
     * @param data The data for the request.
     * @param data.requestBody
     * @returns BatchDownloadResponse Successful Response
     * @throws ApiError
     */
    public static batchDownloadAssets(data: BatchDownloadBatchDownloadAssetsData): CancelablePromise<BatchDownloadBatchDownloadAssetsResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/assets/batch-download',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class DownloadService {
    /**
     * Download asset via presigned URL
     * Generate a presigned URL for downloading an asset directly from MinIO.
     * Returns enhanced response with file metadata (file_name, file_size, mime_type).
     *
     * **Authorization:**
     * - User must own the asset, OR
     * - User must be Admin/Supervisor (can access any asset)
     *
     * **URL Validity:**
     * - Download URLs are valid for 1 hour (configurable)
     * - URL uses HMAC-SHA256 signature
     *
     * **Direct Download:**
     * - Client downloads directly from MinIO using the signed URL
     * - No API proxying - reduces server load (NFR-P4, NFR-P5, NFR-P6)
     * - Supports HTTP Range requests for resume capability
     *
     * **Audit Logging:**
     * - Creates audit log entry with action="download" (AC: #5)
     *
     * **Returns:**
     * - 200 OK with presigned URL and file metadata
     * - 403 Forbidden if user lacks permission
     * - 404 Not Found if asset does not exist
     * - 429 Too Many Requests if rate limit exceeded
     * @param data The data for the request.
     * @param data.assetId
     * @returns DownloadResponse Presigned download URL with file metadata
     * @throws ApiError
     */
    public static downloadAsset(data: DownloadDownloadAssetData): CancelablePromise<DownloadDownloadAssetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/assets/{asset_id}/download',
            path: {
                asset_id: data.assetId
            },
            errors: {
                403: 'Permission denied',
                404: 'Asset not found',
                422: 'Validation Error',
                429: 'Rate limit exceeded'
            }
        });
    }
}

export class HealthService {
    /**
     * Health Check
     * Health check endpoint for monitoring systems.
     *
     * Checks PostgreSQL and MinIO connectivity with timeout handling.
     * Returns 200 if all healthy, 503 if any component unhealthy.
     * @returns HealthCheckResponse All systems healthy
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<HealthHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/health',
            errors: {
                503: 'One or more systems unhealthy'
            }
        });
    }
}

export class ItemsService {
    /**
     * Read Items
     * Retrieve items.
     *
     * Rate limited based on user role (Story 2.4).
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ItemsPublic Successful Response
     * @throws ApiError
     */
    public static readItems(data: ItemsReadItemsData = {}): CancelablePromise<ItemsReadItemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Item
     * Create new item.
     *
     * Rate limited based on user role (Story 2.4).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static createItem(data: ItemsCreateItemData): CancelablePromise<ItemsCreateItemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/items/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Item
     * Get item by ID.
     *
     * Rate limited based on user role (Story 2.4).
     * @param data The data for the request.
     * @param data.id
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static readItem(data: ItemsReadItemData): CancelablePromise<ItemsReadItemResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Item
     * Update an item.
     *
     * Rate limited based on user role (Story 2.4).
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static updateItem(data: ItemsUpdateItemData): CancelablePromise<ItemsUpdateItemResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Item
     * Delete an item.
     *
     * Rate limited based on user role (Story 2.4).
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteItem(data: ItemsDeleteItemData): CancelablePromise<ItemsDeleteItemResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PreviewService {
    /**
     * Get asset preview URL
     * Get a preview URL for an asset based on its type.
     *
     * Returns a presigned URL appropriate for inline preview:
     * - **Images** (JPEG, PNG, GIF, WebP, SVG): Direct URL for `<img>` tag
     * - **Videos** (MP4, WebM, OGG, QuickTime): URL for `<video>` tag with controls
     * - **Audio** (MP3, WAV, OGG, AAC): URL for `<audio>` tag with controls
     * - **PDFs**: URL for iframe or PDF.js viewer
     * - **Documents** (JSON, Plain Text, HTML, CSS, JS): URL for code/text viewer
     * - **Unsupported**: Returns null URL with file metadata only
     *
     * **Preview URLs:**
     * - Valid for 1 hour (AC: #8)
     * - Browser renders content directly from MinIO (zero-proxy architecture)
     * - HTTP Range support for video/audio seeking
     *
     * **Permission:** User must own the asset or be Admin/Supervisor (AC: #10).
     *
     * **Error codes:**
     * - 403 PERMISSION_DENIED: User lacks permission
     * - 404 ASSET_NOT_FOUND: Asset does not exist
     * @param data The data for the request.
     * @param data.assetId
     * @returns PreviewResponse Successful Response
     * @throws ApiError
     */
    public static previewAsset(data: PreviewPreviewAssetData): CancelablePromise<PreviewPreviewAssetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/assets/{asset_id}/preview',
            path: {
                asset_id: data.assetId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class SignedUrlsService {
    /**
     * Generate presigned download URL
     * Generate a presigned URL for downloading an asset directly from MinIO.
     *
     * **Authorization:**
     * - User must own the asset, OR
     * - User must be Admin/Supervisor (can access any asset)
     *
     * **URL Validity:**
     * - Download URLs are valid for 1 hour (configurable)
     * - URL uses HMAC-SHA256 signature
     *
     * **Direct Download:**
     * - Client downloads directly from MinIO using the signed URL
     * - No API proxying - reduces server load (NFR-P4, NFR-P5, NFR-P6)
     *
     * **Returns:**
     * - 200 OK with presigned URL and expiration timestamp
     * - 403 Forbidden if user lacks permission
     * - 404 Not Found if asset does not exist
     * - 429 Too Many Requests if rate limit exceeded
     * @param data The data for the request.
     * @param data.assetId
     * @returns SignedURLResponse Presigned URL generated successfully
     * @throws ApiError
     */
    public static getDownloadUrl(data: SignedUrlsGetDownloadUrlData): CancelablePromise<SignedUrlsGetDownloadUrlResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/assets/{asset_id}/download-url',
            path: {
                asset_id: data.assetId
            },
            errors: {
                403: 'Permission denied',
                404: 'Asset not found',
                422: 'Validation Error',
                429: 'Rate limit exceeded'
            }
        });
    }
    
    /**
     * Generate presigned stream URL
     * Generate a presigned URL for streaming video/audio assets directly from MinIO.
     *
     * **Use Case:**
     * - Video players with seek support (HTTP Range requests)
     * - Audio streaming
     * - Progressive download for large media files
     *
     * **Authorization:**
     * - User must own the asset, OR
     * - User must be Admin/Supervisor (can access any asset)
     *
     * **URL Validity:**
     * - Stream URLs are valid for 1 hour (configurable)
     * - URL supports HTTP Range requests for seeking
     *
     * **Returns:**
     * - 200 OK with presigned URL and expiration timestamp
     * - 403 Forbidden if user lacks permission
     * - 404 Not Found if asset does not exist
     * @param data The data for the request.
     * @param data.assetId
     * @returns SignedURLResponse Presigned stream URL generated successfully
     * @throws ApiError
     */
    public static getStreamUrl(data: SignedUrlsGetStreamUrlData): CancelablePromise<SignedUrlsGetStreamUrlResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/assets/{asset_id}/stream-url',
            path: {
                asset_id: data.assetId
            },
            errors: {
                403: 'Permission denied',
                404: 'Asset not found',
                422: 'Validation Error',
                429: 'Rate limit exceeded'
            }
        });
    }
    
    /**
     * Generate presigned upload URL
     * Generate a presigned URL for uploading a new asset directly to MinIO.
     *
     * **Workflow:**
     * 1. Client requests upload URL with file metadata
     * 2. Server validates file type and generates presigned PUT URL
     * 3. Server pre-generates asset ID and object key
     * 4. Client uploads directly to MinIO using the signed URL
     * 5. (Future) Client confirms upload to create asset metadata
     *
     * **Validation:**
     * - MIME type must be in allowed whitelist
     * - File name must be valid (no path traversal)
     *
     * **URL Validity:**
     * - Upload URLs are valid for 15 minutes (short for security)
     * - URL allows single PUT request
     *
     * **Returns:**
     * - 200 OK with presigned URL, expiration, asset_id, and object_key
     * - 400 Bad Request if file type not allowed or filename invalid
     * - 429 Too Many Requests if rate limit exceeded
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UploadURLResponse Presigned upload URL generated successfully
     * @throws ApiError
     */
    public static getUploadUrl(data: SignedUrlsGetUploadUrlData): CancelablePromise<SignedUrlsGetUploadUrlResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/assets/upload-url',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                400: 'Validation error',
                422: 'Validation Error',
                429: 'Rate limit exceeded'
            }
        });
    }
}

export class StreamingService {
    /**
     * Stream video or audio asset
     * Stream a video or audio asset via presigned URL with HTTP Range support.
     *
     * The returned URL supports HTTP Range requests for seeking and progressive playback.
     * URL is valid for 1 hour.
     *
     * **Supported formats:**
     * - Video: MP4, WebM, OGG, QuickTime
     * - Audio: MP3, WAV, OGG, WebM, AAC
     *
     * **HTTP Range Support:**
     * The returned URL supports Range headers for seeking:
     * - Request: `Range: bytes=1000000-2000000`
     * - Response: `206 Partial Content` with requested bytes
     *
     * **Permission:** User must own the asset or be Admin/Supervisor.
     *
     * **Error codes:**
     * - 400 INVALID_ASSET_TYPE: Asset is not video/audio
     * - 403 PERMISSION_DENIED: User lacks permission
     * - 404 ASSET_NOT_FOUND: Asset does not exist
     * @param data The data for the request.
     * @param data.assetId
     * @returns StreamingURLResponse Successful Response
     * @throws ApiError
     */
    public static streamAsset(data: StreamingStreamAssetData): CancelablePromise<StreamingStreamAssetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/assets/{asset_id}/stream',
            path: {
                asset_id: data.assetId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users with optional filtering.
     *
     * - **role**: Filter by user role (optional)
     * - **tenant_id**: Filter by tenant (optional)
     *
     * Requires Admin or Supervisor role (Story 2.5, AC: #6, #7).
     * Rate limited based on user role - Admins/Supervisors have unlimited access (Story 2.4).
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @param data.role
     * @param data.tenantId
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit,
                role: data.role,
                tenant_id: data.tenantId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     *
     * Requires Admin or Supervisor role (Story 2.5).
     * Rate limited based on user role - Admins/Supervisors have unlimited access (Story 2.4).
     * Logs user creation in audit_logs (Story 2.5, AC: #10).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     *
     * Rate limited based on user role (Story 2.4).
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     *
     * Rate limited based on user role (Story 2.4).
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     *
     * Rate limited based on user role (Story 2.4).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     *
     * Rate limited based on user role (Story 2.4).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     *
     * Rate limited by IP to prevent abuse (configurable via RATE_LIMIT_SIGNUP).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     *
     * Returns user details including role, tenant_id, created_at, updated_at.
     * Rate limited based on user role (Story 2.4).
     * Admins and Supervisors can view any user (Story 2.5, AC: #4).
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     *
     * Requires Admin or Supervisor role (Story 2.5, AC: #5).
     * Rate limited based on user role - Admins/Supervisors have unlimited access (Story 2.4).
     * Logs changes in audit_logs (Story 2.5, AC: #10).
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     *
     * Requires Admin or Supervisor role (Story 2.5, AC: #8).
     * Rate limited based on user role - Admins/Supervisors have unlimited access (Story 2.4).
     * Logs deletion in audit_logs (Story 2.5, AC: #10).
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}