// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { AssetsUploadFileData, AssetsUploadFileResponse, AssetsUploadZipData, AssetsUploadZipResponse, AuthLoginData, AuthLoginResponse, AuthRefreshTokenData, AuthRefreshTokenResponse, HealthHealthCheckResponse, ItemsReadItemsData, ItemsReadItemsResponse, ItemsCreateItemData, ItemsCreateItemResponse, ItemsReadItemData, ItemsReadItemResponse, ItemsUpdateItemData, ItemsUpdateItemResponse, ItemsDeleteItemData, ItemsDeleteItemResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PrivateCreateUserData, PrivateCreateUserResponse, SignedUrlsGetDownloadUrlData, SignedUrlsGetDownloadUrlResponse, SignedUrlsGetStreamUrlData, SignedUrlsGetStreamUrlResponse, SignedUrlsGetUploadUrlData, SignedUrlsGetUploadUrlResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse, ValidationGetValidationRulesResponse } from './types.gen';

export class AssetsService {
    /**
     * Upload a single file
     * Upload a single file to user's storage area.
     *
     * **Validation:**
     * - MIME type must be in allowed whitelist (AC: #2)
     * - File size must not exceed type-specific limits (AC: #1)
     * - Videos: 10GB max
     * - Images: 500MB max
     * - Other: 5GB max
     *
     * **Process:**
     * 1. Validates file type and size
     * 2. Uploads to MinIO with streaming (no full memory buffering)
     * 3. Calculates MD5 checksum during upload
     * 4. Creates asset metadata in PostgreSQL
     * 5. Creates audit log entry
     *
     * **Returns:**
     * - 201 Created with asset metadata on success
     * - 400 Bad Request with INVALID_FILE_TYPE if MIME type not allowed
     * - 400 Bad Request with FILE_TOO_LARGE if size exceeds limit
     * - 401 Unauthorized if not authenticated
     * - 429 Too Many Requests if rate limit exceeded
     * @param data The data for the request.
     * @param data.formData
     * @returns AssetResponse File uploaded successfully
     * @throws ApiError
     */
    public static uploadFile(data: AssetsUploadFileData): CancelablePromise<AssetsUploadFileResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/assets/upload',
            formData: data.formData,
            mediaType: 'multipart/form-data',
            errors: {
                400: 'Validation error (invalid type or size)',
                401: 'Not authenticated',
                422: 'Validation Error',
                429: 'Rate limit exceeded'
            }
        });
    }
    
    /**
     * Upload and extract a ZIP archive
     * Upload a ZIP archive and extract its contents to user's storage area.
     *
     * **Authorization:** Only publishers and teachers can upload ZIP archives (AC: #2).
     *
     * **Process:**
     * 1. Validates user role (publisher/teacher only)
     * 2. Validates ZIP file format and size
     * 3. Extracts contents with streaming (no full memory buffering)
     * 4. Filters system files (.DS_Store, __MACOSX/, etc.) (AC: #4)
     * 5. Validates each extracted file (MIME type, size)
     * 6. Uploads valid files to MinIO preserving folder structure (AC: #7)
     * 7. Creates asset metadata for each extracted file (AC: #8)
     * 8. Creates audit log entries (AC: #11)
     *
     * **ZIP Limits:**
     * - Maximum ZIP file size: 10GB
     * - Maximum extracted files: 1000
     * - Maximum total extracted size: 50GB
     *
     * **Returns:**
     * - 201 Created with extraction results on success
     * - 400 Bad Request with INVALID_ZIP_FILE if ZIP is corrupt (AC: #13)
     * - 400 Bad Request with ZIP_BOMB_DETECTED if zip bomb suspected
     * - 401 Unauthorized if not authenticated
     * - 403 Forbidden if user role not authorized (AC: #14)
     * - 413 Request Entity Too Large if ZIP exceeds size limit
     * - 429 Too Many Requests if rate limit exceeded
     * @param data The data for the request.
     * @param data.formData
     * @returns ZipUploadResponse ZIP extracted successfully
     * @throws ApiError
     */
    public static uploadZip(data: AssetsUploadZipData): CancelablePromise<AssetsUploadZipResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/assets/upload-zip',
            formData: data.formData,
            mediaType: 'multipart/form-data',
            errors: {
                400: 'Invalid ZIP file or zip bomb detected',
                401: 'Not authenticated',
                403: 'User role not authorized for ZIP uploads',
                413: 'ZIP file too large',
                422: 'Validation Error',
                429: 'Rate limit exceeded'
            }
        });
    }
}

export class AuthService {
    /**
     * Login
     * OAuth2 compatible login endpoint.
     *
     * Accepts email/password and returns access + refresh tokens.
     *
     * **Rate Limited:** Configurable via RATE_LIMIT_LOGIN (default: 5/minute per IP)
     *
     * - **username**: User's email address
     * - **password**: User's password
     *
     * Returns:
     * TokenResponse with access_token, refresh_token, token_type, expires_in
     *
     * Raises:
     * - 401: Invalid credentials or inactive account
     * - 429: Too many requests (rate limit exceeded)
     * @param data The data for the request.
     * @param data.formData
     * @returns TokenResponse Successful Response
     * @throws ApiError
     */
    public static login(data: AuthLoginData): CancelablePromise<AuthLoginResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/auth/login',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Refresh Token
     * Refresh access token using refresh token.
     *
     * Implements token rotation - new refresh token is issued with each refresh (AC: #7).
     *
     * - **refresh_token**: Valid refresh token from previous login
     *
     * Returns:
     * TokenResponse with new access_token and refresh_token
     *
     * Raises:
     * - 401: Invalid or expired refresh token
     * @param data The data for the request.
     * @param data.requestBody
     * @returns TokenResponse Successful Response
     * @throws ApiError
     */
    public static refreshToken(data: AuthRefreshTokenData): CancelablePromise<AuthRefreshTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/auth/refresh',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class HealthService {
    /**
     * Health Check
     * Health check endpoint for monitoring systems.
     *
     * Checks PostgreSQL and MinIO connectivity with timeout handling.
     * Returns 200 if all healthy, 503 if any component unhealthy.
     * @returns HealthCheckResponse All systems healthy
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<HealthHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/health',
            errors: {
                503: 'One or more systems unhealthy'
            }
        });
    }
}

export class ItemsService {
    /**
     * Read Items
     * Retrieve items.
     *
     * Rate limited based on user role (Story 2.4).
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ItemsPublic Successful Response
     * @throws ApiError
     */
    public static readItems(data: ItemsReadItemsData = {}): CancelablePromise<ItemsReadItemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Item
     * Create new item.
     *
     * Rate limited based on user role (Story 2.4).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static createItem(data: ItemsCreateItemData): CancelablePromise<ItemsCreateItemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/items/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Item
     * Get item by ID.
     *
     * Rate limited based on user role (Story 2.4).
     * @param data The data for the request.
     * @param data.id
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static readItem(data: ItemsReadItemData): CancelablePromise<ItemsReadItemResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Item
     * Update an item.
     *
     * Rate limited based on user role (Story 2.4).
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static updateItem(data: ItemsUpdateItemData): CancelablePromise<ItemsUpdateItemResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Item
     * Delete an item.
     *
     * Rate limited based on user role (Story 2.4).
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteItem(data: ItemsDeleteItemData): CancelablePromise<ItemsDeleteItemResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class SignedUrlsService {
    /**
     * Generate presigned download URL
     * Generate a presigned URL for downloading an asset directly from MinIO.
     *
     * **Authorization:**
     * - User must own the asset, OR
     * - User must be Admin/Supervisor (can access any asset)
     *
     * **URL Validity:**
     * - Download URLs are valid for 1 hour (configurable)
     * - URL uses HMAC-SHA256 signature
     *
     * **Direct Download:**
     * - Client downloads directly from MinIO using the signed URL
     * - No API proxying - reduces server load (NFR-P4, NFR-P5, NFR-P6)
     *
     * **Returns:**
     * - 200 OK with presigned URL and expiration timestamp
     * - 403 Forbidden if user lacks permission
     * - 404 Not Found if asset does not exist
     * - 429 Too Many Requests if rate limit exceeded
     * @param data The data for the request.
     * @param data.assetId
     * @returns SignedURLResponse Presigned URL generated successfully
     * @throws ApiError
     */
    public static getDownloadUrl(data: SignedUrlsGetDownloadUrlData): CancelablePromise<SignedUrlsGetDownloadUrlResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/assets/{asset_id}/download-url',
            path: {
                asset_id: data.assetId
            },
            errors: {
                403: 'Permission denied',
                404: 'Asset not found',
                422: 'Validation Error',
                429: 'Rate limit exceeded'
            }
        });
    }
    
    /**
     * Generate presigned stream URL
     * Generate a presigned URL for streaming video/audio assets directly from MinIO.
     *
     * **Use Case:**
     * - Video players with seek support (HTTP Range requests)
     * - Audio streaming
     * - Progressive download for large media files
     *
     * **Authorization:**
     * - User must own the asset, OR
     * - User must be Admin/Supervisor (can access any asset)
     *
     * **URL Validity:**
     * - Stream URLs are valid for 1 hour (configurable)
     * - URL supports HTTP Range requests for seeking
     *
     * **Returns:**
     * - 200 OK with presigned URL and expiration timestamp
     * - 403 Forbidden if user lacks permission
     * - 404 Not Found if asset does not exist
     * @param data The data for the request.
     * @param data.assetId
     * @returns SignedURLResponse Presigned stream URL generated successfully
     * @throws ApiError
     */
    public static getStreamUrl(data: SignedUrlsGetStreamUrlData): CancelablePromise<SignedUrlsGetStreamUrlResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/assets/{asset_id}/stream-url',
            path: {
                asset_id: data.assetId
            },
            errors: {
                403: 'Permission denied',
                404: 'Asset not found',
                422: 'Validation Error',
                429: 'Rate limit exceeded'
            }
        });
    }
    
    /**
     * Generate presigned upload URL
     * Generate a presigned URL for uploading a new asset directly to MinIO.
     *
     * **Workflow:**
     * 1. Client requests upload URL with file metadata
     * 2. Server validates file type and generates presigned PUT URL
     * 3. Server pre-generates asset ID and object key
     * 4. Client uploads directly to MinIO using the signed URL
     * 5. (Future) Client confirms upload to create asset metadata
     *
     * **Validation:**
     * - MIME type must be in allowed whitelist
     * - File name must be valid (no path traversal)
     *
     * **URL Validity:**
     * - Upload URLs are valid for 15 minutes (short for security)
     * - URL allows single PUT request
     *
     * **Returns:**
     * - 200 OK with presigned URL, expiration, asset_id, and object_key
     * - 400 Bad Request if file type not allowed or filename invalid
     * - 429 Too Many Requests if rate limit exceeded
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UploadURLResponse Presigned upload URL generated successfully
     * @throws ApiError
     */
    public static getUploadUrl(data: SignedUrlsGetUploadUrlData): CancelablePromise<SignedUrlsGetUploadUrlResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/assets/upload-url',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                400: 'Validation error',
                422: 'Validation Error',
                429: 'Rate limit exceeded'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users with optional filtering.
     *
     * - **role**: Filter by user role (optional)
     * - **tenant_id**: Filter by tenant (optional)
     *
     * Requires Admin or Supervisor role (Story 2.5, AC: #6, #7).
     * Rate limited based on user role - Admins/Supervisors have unlimited access (Story 2.4).
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @param data.role
     * @param data.tenantId
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit,
                role: data.role,
                tenant_id: data.tenantId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     *
     * Requires Admin or Supervisor role (Story 2.5).
     * Rate limited based on user role - Admins/Supervisors have unlimited access (Story 2.4).
     * Logs user creation in audit_logs (Story 2.5, AC: #10).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     *
     * Rate limited based on user role (Story 2.4).
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     *
     * Rate limited based on user role (Story 2.4).
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     *
     * Rate limited based on user role (Story 2.4).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     *
     * Rate limited based on user role (Story 2.4).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     *
     * Rate limited by IP to prevent abuse (configurable via RATE_LIMIT_SIGNUP).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     *
     * Returns user details including role, tenant_id, created_at, updated_at.
     * Rate limited based on user role (Story 2.4).
     * Admins and Supervisors can view any user (Story 2.5, AC: #4).
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     *
     * Requires Admin or Supervisor role (Story 2.5, AC: #5).
     * Rate limited based on user role - Admins/Supervisors have unlimited access (Story 2.4).
     * Logs changes in audit_logs (Story 2.5, AC: #10).
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     *
     * Requires Admin or Supervisor role (Story 2.5, AC: #8).
     * Rate limited based on user role - Admins/Supervisors have unlimited access (Story 2.4).
     * Logs deletion in audit_logs (Story 2.5, AC: #10).
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}

export class ValidationService {
    /**
     * Get file validation rules
     * Returns the current file validation rules for client-side pre-validation.
     *
     * **Use this endpoint to:**
     * - Show allowed file types in upload UI
     * - Validate files before upload attempt (reduce failed uploads)
     * - Display size limits to users
     * - Build file type filters for file picker dialogs
     * - Show blocked file extensions
     *
     * **This endpoint does NOT require authentication** - validation rules
     * are public information needed by the frontend.
     *
     * **Response includes:**
     * - `allowed_mime_types`: List of MIME types accepted by the server
     * - `size_limits`: Maximum file size per category (video, image, audio, default)
     * - `extension_mappings`: Which extensions map to which MIME types
     * - `max_filename_length`: Maximum allowed filename length
     * - `dangerous_extensions`: Extensions that are always blocked for security
     * @returns ValidationRulesResponse Validation rules returned successfully
     * @throws ApiError
     */
    public static getValidationRules(): CancelablePromise<ValidationGetValidationRulesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/upload/validation-rules'
        });
    }
}