// This file is auto-generated by @hey-api/openapi-ts

/**
 * Response schema for asset operations (AC: #6).
 *
 * Returned on successful upload with 201 Created.
 */
export type AssetResponse = {
    /**
     * Unique asset identifier
     */
    asset_id: string;
    /**
     * Original filename (sanitized)
     */
    file_name: string;
    /**
     * File size in bytes
     */
    file_size_bytes: number;
    /**
     * MIME type of the file
     */
    mime_type: string;
    /**
     * MD5 checksum for integrity verification
     */
    checksum: (string | null);
    /**
     * MinIO object key (storage path)
     */
    object_key: string;
    /**
     * MinIO bucket name
     */
    bucket: string;
    /**
     * Owner user ID
     */
    user_id: string;
    /**
     * Tenant ID
     */
    tenant_id: string;
    /**
     * Soft delete flag
     */
    is_deleted: boolean;
    /**
     * Upload timestamp
     */
    created_at: string;
    /**
     * Last update timestamp
     */
    updated_at: string;
};

/**
 * Request schema for batch download endpoint (AC: #1, #11, #12).
 *
 * Validates:
 * - Non-empty asset list (min 1)
 * - Maximum 100 assets per request
 * - No duplicate asset IDs
 *
 * References:
 * - Task 2.2: Request schema with validation
 * - AC: #11 (empty list), #12 (too many assets)
 */
export type BatchDownloadRequest = {
    /**
     * List of asset IDs to include in batch download (1-100 assets)
     */
    asset_ids: Array<(string)>;
};

/**
 * Response schema for batch download endpoint (AC: #4).
 *
 * Contains:
 * - Presigned download URL for the generated ZIP
 * - Expiration time (1 hour, AC: #5, #8)
 * - File metadata (count, sizes)
 *
 * References:
 * - Task 2.3: Response schema
 * - AC: #4 (download URL), #5 (expiry)
 */
export type BatchDownloadResponse = {
    /**
     * Presigned URL to download the generated ZIP file
     */
    download_url: string;
    /**
     * URL and ZIP file expiration time (1 hour from creation)
     */
    expires_at: string;
    /**
     * Generated ZIP file name
     */
    file_name: string;
    /**
     * Number of files included in the ZIP
     */
    file_count: number;
    /**
     * Total size of all files before compression
     */
    total_size_bytes: number;
    /**
     * Size of the ZIP file
     */
    compressed_size_bytes: number;
};

export type Body_assets_upload_file = {
    /**
     * File to upload
     */
    file: (Blob | File);
};

export type Body_auth_login = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * Response schema for asset download endpoint.
 *
 * Returns presigned download URL with complete file metadata.
 *
 * References:
 * - AC: #3 (enhanced download response)
 * - Task 2.2 (schema fields)
 */
export type DownloadResponse = {
    /**
     * Presigned URL for direct MinIO download (1-hour TTL)
     */
    download_url: string;
    /**
     * URL expiration time in ISO-8601 format
     */
    expires_at: string;
    /**
     * Original file name
     */
    file_name: string;
    /**
     * File size in bytes
     */
    file_size: number;
    /**
     * MIME type of the file
     */
    mime_type: string;
};

/**
 * Health check response schema.
 */
export type HealthCheckResponse = {
    status: 'healthy' | 'unhealthy';
    database: 'ok' | 'error';
    minio: 'ok' | 'error';
    timestamp: string;
};

export type status = 'healthy' | 'unhealthy';

export type database = 'ok' | 'error';

export type minio = 'ok' | 'error';

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Properties to receive on item creation.
 */
export type ItemCreate = {
    title: string;
    description?: (string | null);
};

/**
 * Properties to return via API.
 */
export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

/**
 * Paginated list of items.
 */
export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

/**
 * Properties to receive on item update.
 */
export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

/**
 * Generic message response.
 */
export type Message = {
    message: string;
};

/**
 * Properties for password reset.
 */
export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * Response schema for asset preview endpoint (AC: #1, #8, #9).
 *
 * Returns a presigned URL appropriate for inline preview based on asset type.
 * For unsupported types, returns null URL with file metadata only.
 *
 * Attributes:
 * preview_url: Presigned URL for preview (null for unsupported types)
 * preview_type: Type of preview (image, video, audio, pdf, document, unsupported)
 * expires_at: URL expiration timestamp (null for unsupported types)
 * mime_type: Original MIME type of the asset
 * file_name: Original file name
 * file_size: File size in bytes
 * supports_inline: Whether the asset can be previewed inline in browser
 */
export type PreviewResponse = {
    /**
     * Presigned URL for preview (null for unsupported types)
     */
    preview_url?: (string | null);
    /**
     * Type of preview: image, video, audio, pdf, document, unsupported
     */
    preview_type: PreviewType;
    /**
     * URL expiration time (ISO-8601, null for unsupported types)
     */
    expires_at?: (string | null);
    /**
     * Original MIME type of the asset
     */
    mime_type: string;
    /**
     * Original file name
     */
    file_name: string;
    /**
     * File size in bytes
     */
    file_size: number;
    /**
     * Whether the asset can be previewed inline in browser
     */
    supports_inline: boolean;
};

/**
 * Types of asset previews supported.
 *
 * Determines how the frontend should render the preview:
 * - image: Display in <img> tag
 * - video: Display in <video> tag with controls
 * - audio: Display in <audio> tag with controls
 * - pdf: Display in <iframe> or PDF.js viewer
 * - document: Display in code/text viewer
 * - unsupported: No inline preview, download only
 */
export type PreviewType = 'image' | 'video' | 'audio' | 'pdf' | 'document' | 'unsupported';

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Request body for token refresh endpoint (AC: #7).
 */
export type RefreshTokenRequest = {
    refresh_token: string;
};

/**
 * Response schema for signed URL generation (AC: #9).
 *
 * Returned when a presigned URL is successfully generated.
 */
export type SignedURLResponse = {
    /**
     * Presigned URL for direct MinIO access
     */
    url: string;
    /**
     * URL expiration time (ISO-8601)
     */
    expires_at: string;
    /**
     * Type of signed URL operation
     */
    type: 'download' | 'upload' | 'stream';
};

/**
 * Type of signed URL operation
 */
export type type = 'download' | 'upload' | 'stream';

/**
 * Response schema for streaming endpoint.
 *
 * Returns presigned URL for video/audio streaming with HTTP Range support.
 * URL is valid for 1 hour (PRESIGNED_URL_STREAM_EXPIRES_SECONDS).
 *
 * References:
 * - Task 2: Streaming response schema
 * - AC: #2, #6 (stream URL with expiration and metadata)
 */
export type StreamingURLResponse = {
    /**
     * Presigned URL for MinIO streaming (supports HTTP Range requests)
     */
    stream_url: string;
    /**
     * URL expiration time (ISO-8601)
     */
    expires_at: string;
    /**
     * Content MIME type (video* or audio*)
     */
    mime_type: string;
    /**
     * Total file size in bytes
     */
    file_size: number;
    /**
     * Original file name
     */
    file_name: string;
    /**
     * Media duration in seconds (if available in metadata)
     */
    duration_seconds?: (number | null);
};

/**
 * JSON payload containing access token (legacy, for backward compatibility).
 */
export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * Full token response with access and refresh tokens (AC: #1, #7).
 */
export type TokenResponse = {
    access_token: string;
    refresh_token: string;
    token_type?: string;
    expires_in: number;
};

/**
 * Properties for password update.
 */
export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

/**
 * Request schema for presigned upload URL generation.
 *
 * Validates file_name and mime_type before generating upload URL.
 */
export type UploadURLRequest = {
    /**
     * Name of the file to upload
     */
    file_name: string;
    /**
     * MIME type of the file
     */
    mime_type: string;
    /**
     * Size of the file in bytes
     */
    file_size: number;
};

/**
 * Response schema for presigned upload URL generation.
 *
 * Includes the upload URL, expiration, and the asset_id for the new asset.
 */
export type UploadURLResponse = {
    /**
     * Presigned URL for direct MinIO upload
     */
    url: string;
    /**
     * URL expiration time (ISO-8601)
     */
    expires_at: string;
    /**
     * URL type
     */
    type?: "upload";
    /**
     * Pre-generated asset ID for the upload
     */
    asset_id: string;
    /**
     * MinIO object key where file will be stored
     */
    object_key: string;
};

/**
 * Properties to receive via API on user creation.
 */
export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    password: string;
    tenant_id?: (string | null);
};

/**
 * Properties to return via API.
 */
export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    id: string;
    tenant_id: (string | null);
    created_at: string;
    updated_at: string;
};

/**
 * Properties for user self-registration.
 */
export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

/**
 * User roles for role-based access control (RBAC).
 */
export type UserRole = 'admin' | 'supervisor' | 'publisher' | 'school' | 'teacher' | 'student';

/**
 * Paginated list of users.
 */
export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

/**
 * Properties to receive via API on user update, all optional.
 */
export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: (UserRole | null);
    password?: (string | null);
    tenant_id?: (string | null);
};

/**
 * Properties for user to update their own profile.
 */
export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AssetsUploadFileData = {
    formData: Body_assets_upload_file;
};

export type AssetsUploadFileResponse = (AssetResponse);

export type AuthLoginData = {
    formData: Body_auth_login;
};

export type AuthLoginResponse = (TokenResponse);

export type AuthRefreshTokenData = {
    requestBody: RefreshTokenRequest;
};

export type AuthRefreshTokenResponse = (TokenResponse);

export type BatchDownloadBatchDownloadAssetsData = {
    requestBody: BatchDownloadRequest;
};

export type BatchDownloadBatchDownloadAssetsResponse = (BatchDownloadResponse);

export type DownloadDownloadAssetData = {
    assetId: string;
};

export type DownloadDownloadAssetResponse = (DownloadResponse);

export type HealthHealthCheckResponse = (HealthCheckResponse);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PreviewPreviewAssetData = {
    assetId: string;
};

export type PreviewPreviewAssetResponse = (PreviewResponse);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SignedUrlsGetDownloadUrlData = {
    assetId: string;
};

export type SignedUrlsGetDownloadUrlResponse = (SignedURLResponse);

export type SignedUrlsGetStreamUrlData = {
    assetId: string;
};

export type SignedUrlsGetStreamUrlResponse = (SignedURLResponse);

export type SignedUrlsGetUploadUrlData = {
    requestBody: UploadURLRequest;
};

export type SignedUrlsGetUploadUrlResponse = (UploadURLResponse);

export type StreamingStreamAssetData = {
    assetId: string;
};

export type StreamingStreamAssetResponse = (StreamingURLResponse);

export type UsersReadUsersData = {
    limit?: number;
    role?: (UserRole | null);
    skip?: number;
    tenantId?: (string | null);
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);