// This file is auto-generated by @hey-api/openapi-ts

export type Body_auth_login = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * Health check response schema.
 */
export type HealthCheckResponse = {
    status: 'healthy' | 'unhealthy';
    database: 'ok' | 'error';
    minio: 'ok' | 'error';
    timestamp: string;
};

export type status = 'healthy' | 'unhealthy';

export type database = 'ok' | 'error';

export type minio = 'ok' | 'error';

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Properties to receive on item creation.
 */
export type ItemCreate = {
    title: string;
    description?: (string | null);
};

/**
 * Properties to return via API.
 */
export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

/**
 * Paginated list of items.
 */
export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

/**
 * Properties to receive on item update.
 */
export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

/**
 * Generic message response.
 */
export type Message = {
    message: string;
};

/**
 * Properties for password reset.
 */
export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Request body for token refresh endpoint (AC: #7).
 */
export type RefreshTokenRequest = {
    refresh_token: string;
};

/**
 * JSON payload containing access token (legacy, for backward compatibility).
 */
export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * Full token response with access and refresh tokens (AC: #1, #7).
 */
export type TokenResponse = {
    access_token: string;
    refresh_token: string;
    token_type?: string;
    expires_in: number;
};

/**
 * Properties for password update.
 */
export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

/**
 * Properties to receive via API on user creation.
 */
export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    password: string;
    tenant_id?: (string | null);
};

/**
 * Properties to return via API.
 */
export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    id: string;
    tenant_id: (string | null);
    created_at: string;
    updated_at: string;
};

/**
 * Properties for user self-registration.
 */
export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

/**
 * User roles for role-based access control (RBAC).
 */
export type UserRole = 'admin' | 'supervisor' | 'publisher' | 'school' | 'teacher' | 'student';

/**
 * Paginated list of users.
 */
export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

/**
 * Properties to receive via API on user update, all optional.
 */
export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: (UserRole | null);
    password?: (string | null);
    tenant_id?: (string | null);
};

/**
 * Properties for user to update their own profile.
 */
export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AuthLoginData = {
    formData: Body_auth_login;
};

export type AuthLoginResponse = (TokenResponse);

export type AuthRefreshTokenData = {
    requestBody: RefreshTokenRequest;
};

export type AuthRefreshTokenResponse = (TokenResponse);

export type HealthHealthCheckResponse = (HealthCheckResponse);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);