"""Add multi-tenant models

Revision ID: b198e225ee29
Revises: 1a31ce608336
Create Date: 2025-12-15 17:42:26.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = 'b198e225ee29'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create enum types first
    userrole_enum = postgresql.ENUM('ADMIN', 'SUPERVISOR', 'PUBLISHER', 'SCHOOL', 'TEACHER', 'STUDENT', name='userrole', create_type=False)
    userrole_enum.create(op.get_bind(), checkfirst=True)

    tenanttype_enum = postgresql.ENUM('PUBLISHER', 'SCHOOL', 'TEACHER', 'STUDENT', name='tenanttype', create_type=False)
    tenanttype_enum.create(op.get_bind(), checkfirst=True)

    auditaction_enum = postgresql.ENUM('UPLOAD', 'DOWNLOAD', 'DELETE', 'RESTORE', 'UPDATE', 'LOGIN', 'LOGOUT', name='auditaction', create_type=False)
    auditaction_enum.create(op.get_bind(), checkfirst=True)

    # Create tenant table first (referenced by user and asset)
    op.create_table('tenant',
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('tenant_type', postgresql.ENUM('PUBLISHER', 'SCHOOL', 'TEACHER', 'STUDENT', name='tenanttype', create_type=False), nullable=False),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_index('ix_tenant_name', 'tenant', ['name'], unique=True)

    # Add new columns to user table
    op.add_column('user', sa.Column('role', postgresql.ENUM('ADMIN', 'SUPERVISOR', 'PUBLISHER', 'SCHOOL', 'TEACHER', 'STUDENT', name='userrole', create_type=False), nullable=False, server_default='STUDENT'))
    op.add_column('user', sa.Column('tenant_id', sa.Uuid(), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('NOW()')))
    op.create_index('ix_user_tenant_id', 'user', ['tenant_id'], unique=False)
    op.create_foreign_key('fk_user_tenant_id', 'user', 'tenant', ['tenant_id'], ['id'])

    # Remove server defaults after data migration
    op.alter_column('user', 'role', server_default=None)
    op.alter_column('user', 'created_at', server_default=None)
    op.alter_column('user', 'updated_at', server_default=None)

    # Create audit_log table
    op.create_table('audit_log',
        sa.Column('action', postgresql.ENUM('UPLOAD', 'DOWNLOAD', 'DELETE', 'RESTORE', 'UPDATE', 'LOGIN', 'LOGOUT', name='auditaction', create_type=False), nullable=False),
        sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
        sa.Column('metadata_json', sa.JSON(), nullable=True),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=True),
        sa.Column('asset_id', sa.Uuid(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_log_asset_id', 'audit_log', ['asset_id'], unique=False)
    op.create_index('idx_audit_log_timestamp', 'audit_log', ['timestamp'], unique=False)
    op.create_index('idx_audit_log_user_id', 'audit_log', ['user_id'], unique=False)
    op.create_index('ix_audit_log_asset_id', 'audit_log', ['asset_id'], unique=False)
    op.create_index('ix_audit_log_timestamp', 'audit_log', ['timestamp'], unique=False)
    op.create_index('ix_audit_log_user_id', 'audit_log', ['user_id'], unique=False)

    # Create asset table
    op.create_table('asset',
        sa.Column('bucket', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('object_key', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
        sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('file_size_bytes', sa.Integer(), nullable=False),
        sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('checksum', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint('file_size_bytes >= 0', name='ck_assets_file_size_positive'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assets_created_at', 'asset', ['created_at'], unique=False)
    op.create_index('idx_assets_tenant_id', 'asset', ['tenant_id'], unique=False)
    op.create_index('idx_assets_tenant_is_deleted', 'asset', ['tenant_id', 'is_deleted'], unique=False)
    op.create_index('idx_assets_user_id', 'asset', ['user_id'], unique=False)
    op.create_index('ix_asset_is_deleted', 'asset', ['is_deleted'], unique=False)
    op.create_index('ix_asset_tenant_id', 'asset', ['tenant_id'], unique=False)
    op.create_index('ix_asset_user_id', 'asset', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop asset table
    op.drop_index('ix_asset_user_id', table_name='asset')
    op.drop_index('ix_asset_tenant_id', table_name='asset')
    op.drop_index('ix_asset_is_deleted', table_name='asset')
    op.drop_index('idx_assets_user_id', table_name='asset')
    op.drop_index('idx_assets_tenant_is_deleted', table_name='asset')
    op.drop_index('idx_assets_tenant_id', table_name='asset')
    op.drop_index('idx_assets_created_at', table_name='asset')
    op.drop_table('asset')

    # Drop audit_log table
    op.drop_index('ix_audit_log_user_id', table_name='audit_log')
    op.drop_index('ix_audit_log_timestamp', table_name='audit_log')
    op.drop_index('ix_audit_log_asset_id', table_name='audit_log')
    op.drop_index('idx_audit_log_user_id', table_name='audit_log')
    op.drop_index('idx_audit_log_timestamp', table_name='audit_log')
    op.drop_index('idx_audit_log_asset_id', table_name='audit_log')
    op.drop_table('audit_log')

    # Remove user columns
    op.drop_constraint('fk_user_tenant_id', 'user', type_='foreignkey')
    op.drop_index('ix_user_tenant_id', table_name='user')
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'tenant_id')
    op.drop_column('user', 'role')

    # Drop tenant table
    op.drop_index('ix_tenant_name', table_name='tenant')
    op.drop_table('tenant')

    # Drop enums
    op.execute('DROP TYPE IF EXISTS userrole')
    op.execute('DROP TYPE IF EXISTS tenanttype')
    op.execute('DROP TYPE IF EXISTS auditaction')
    # ### end Alembic commands ###
